name: myapp
description: Bike rental Startup app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  path_provider: ^2.0.14
  path: ^1.8.2
  sqflite: ^2.2.6
  http: ^0.13.5
  google_maps_flutter: ^2.0.2
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  flutter_bluetooth_serial: ^0.4.0
  awesome_notifications: ^0.7.4+1
  maps_toolkit: ^2.0.1
  dio: ^5.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/-1sj.png
    - assets/page-1/images/.png
    - assets/page-1/images/backgroundnotremoved-2.png
    - assets/page-1/images/black-screen-Rim.png
    - assets/page-1/images/black-screen.png
    - assets/page-1/images/blur.png
    - assets/page-1/images/card.png
    - assets/page-1/images/clock.png
    - assets/page-1/images/cloudly.png
    - assets/page-1/images/compass.png
    - assets/page-1/images/coupon.png
    - assets/page-1/images/distanceicon.png
    - assets/page-1/images/group-141-copy-2.png
    - assets/page-1/images/group-141-copy-3.png
    - assets/page-1/images/group-141-copy-HBs.png
    - assets/page-1/images/group-141-copy-hTT.png
    - assets/page-1/images/group-141-copy-YE9.png
    - assets/page-1/images/group-141-copy-ZqX.png
    - assets/page-1/images/group-141-copy.png
    - assets/page-1/images/group-141.png
    - assets/page-1/images/icon-chevron-left-2iH.png
    - assets/page-1/images/icon-chevron-left-aUm.png
    - assets/page-1/images/icon-chevron-left-bQ9.png
    - assets/page-1/images/icon-chevron-left-CLD.png
    - assets/page-1/images/icon-chevron-left-ECV.png
    - assets/page-1/images/icon-chevron-left-FJD.png
    - assets/page-1/images/icon-chevron-left-iqb.png
    - assets/page-1/images/icon-chevron-left-qQ1.png
    - assets/page-1/images/icon-chevron-left-UAq.png
    - assets/page-1/images/icon-chevron-left-wSu.png
    - assets/page-1/images/icon-chevron-left-XeV.png
    - assets/page-1/images/icon-chevron-left.png
    - assets/page-1/images/icon-log-out.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/image-13-bg.png
    - assets/page-1/images/image-14-goF.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/image-24-m17.png
    - assets/page-1/images/image-24.png
    - assets/page-1/images/image-25-Df3.png
    - assets/page-1/images/image-25-mFb.png
    - assets/page-1/images/image-25.png
    - assets/page-1/images/image-26-HpH.png
    - assets/page-1/images/image-26-YvR.png
    - assets/page-1/images/image-26.png
    - assets/page-1/images/image-27-HNM.png
    - assets/page-1/images/image-27-jwj.png
    - assets/page-1/images/image-27.png
    - assets/page-1/images/image-28-fiD.png
    - assets/page-1/images/image-28.png
    - assets/page-1/images/image-30-NmB.png
    - assets/page-1/images/image-30.png
    - assets/page-1/images/image-31.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/location_not_selected.png
    - assets/page-1/images/location_selected.png
    - assets/page-1/images/lock_selected.png
    - assets/page-1/images/mail.png
    - assets/page-1/images/menu.png
    - assets/page-1/images/nfc_unlocked.png
    - assets/page-1/images/oval-5Uy.png
    - assets/page-1/images/oval-6nR.png
    - assets/page-1/images/oval-82y.png
    - assets/page-1/images/oval-gdB.png
    - assets/page-1/images/oval-HfT.png
    - assets/page-1/images/oval-wyP.png
    - assets/page-1/images/oval-XBB.png
    - assets/page-1/images/oval.png
    - assets/page-1/images/path-copy-2.png
    - assets/page-1/images/path-copy.png
    - assets/page-1/images/path-eub.png
    - assets/page-1/images/path-nW1.png
    - assets/page-1/images/path-qYH.png
    - assets/page-1/images/path-WCu.png
    - assets/page-1/images/path.png
    - assets/page-1/images/profile.png
    - assets/page-1/images/profile_2.png
    - assets/page-1/images/rectangle-277-1u7.png
    - assets/page-1/images/rectangle-277-D3T.png
    - assets/page-1/images/rectangle-277-kp5.png
    - assets/page-1/images/rectangle-277-mZw.png
    - assets/page-1/images/rectangle-277-Q85.png
    - assets/page-1/images/rectangle-277.png
    - assets/page-1/images/rectangle-2zH.png
    - assets/page-1/images/rectangle-ja5.png
    - assets/page-1/images/rectangle-wuF.png
    - assets/page-1/images/rectangle.png
    - assets/page-1/images/refresh_map.png
    - assets/page-1/images/select.png
    - assets/page-1/images/select_1.png
    - assets/page-1/images/select_2.png
    - assets/page-1/images/select_3.png
    - assets/page-1/images/student_id.png
    - assets/page-1/images/takeride_button.png
    - assets/page-1/images/tool.png
    - assets/page-1/images/toolkit_not_slected.png
    - assets/page-1/images/toolkit_selected.png
    - assets/page-1/images/triangle-a1T.png
    - assets/page-1/images/triangle-Y9B.png
    - assets/page-1/images/triangle.png
    - assets/page-1/images/unlock.png
    - assets/page-1/images/unlock_not_selected.png
    - assets/page-1/images/vector-bQR.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/buttonoff.png
    - assets/page-1/images/buttonon.png
    - assets/page-1/images/icon-log-out.png
    - assets/page-1/images/image-32.png
    - assets/page-1/images/rectangle-277.png
    - assets/page-1/images/promotion.png
    - assets/page-1/images/takeride_button.png
    - assets/page-1/images/gps.png
    - assets/page-1/images/nfc_locked.png
    - assets/page-1/images/error.png
    - assets/icons/bike.png
    - assets/icons/bike-parking.png
    - assets/icons/body.png
    - assets/icons/blue_circule.png
    - assets/icons/google_icon.png
    - assets/page-1/images/blur_screen.png
    - assets/page-1/images/payment_code.png
    - assets/page-1/images/image-23.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
